on: [push]
name: ci
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: poetry install
      - run: poetry run black --check src/ tests/
      - run: poetry run mypy src/ tests/
      - run: poetry run ruff check src/ tests/
      - run: poetry run py.test tests/
